#!/usr/bin/env python3
"""gwatt
   Challenge Animal list"""

def main():

    # create a list called animallist
    animallist = ["Fox", "Fly", "Ant", "Bee", "Cod", "Cat", "Dog", "Yak", "Cow", "Hen", "Koi", "Hog", "Jay", "Kit"]

    # Print the list
    print(animallist)

    # Print the bugs
    print("The bugs from the list are: " + animallist[1] + "," + animallist[2] + "," + animallist[3])

main()
